name: Build LaTeX document

on:

  pull_request:
    branches:
      - master 

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0

      - name: Set up Git repository
        uses: actions/checkout@v5
      - run: sudo apt-get update
      - run: sudo apt install fonts-cmu texlive-full python3-pygments --yes    
      - run: cpan PDF::API2  
      - name: build document
        run: latexmk core-design-document.tex
      
      - name: Upload compiled document
        uses: actions/upload-artifact@v4
        with:
          name: core-design-document
          path: core-design-document.pdf